---
name: ci

on:
  push:
    branches: [master]
    paths:
    - 'src/*.rs'
    - 'Cargo.toml'
  pull_request:
    branches: [master]
    paths:
    - 'src/*.rs'
    - 'Cargo.toml'

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: lint
      run: cargo fmt -- --check
    - name: build
      run: cargo build
    - name: test
      run: cargo test -- --show-output
